"""add_companies

Revision ID: 0d44b3fae338
Revises: cf18aa6b903f
Create Date: 2026-07-14 17:45:34.446268
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0d44b3fae338'
down_revision = 'cf18aa6b903f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('license_companies',
    sa.Column('license_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('license_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license_companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
