"""add_imbl_regions

Revision ID: b5ec8cba18f0
Revises: 0d44b3fae338
Create Date: 2026-08-19 15:43:40.923538
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b5ec8cba18f0'
down_revision = '0d44b3fae338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imbl_regions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('imbl_region_municipalities',
    sa.Column('imbl_region_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('municipality_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['imbl_region_id'], ['imbl_regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('imbl_region_id', 'municipality_id')
    )
    op.add_column('licenses', sa.Column('issuing_municipality_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('licenses', sa.Column('imbl_region_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'licenses', 'imbl_regions', ['imbl_region_id'], ['id'])
    op.create_foreign_key(None, 'licenses', 'municipalities', ['issuing_municipality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.drop_column('licenses', 'imbl_region_id')
    op.drop_column('licenses', 'issuing_municipality_id')
    op.drop_table('imbl_region_municipalities')
    op.drop_table('imbl_regions')
    # ### end Alembic commands ###
