"""initial_licensing_schema

Revision ID: cf18aa6b903f
Revises: 
Create Date: 2026-07-07 18:03:36.998122
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cf18aa6b903f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('regional_districts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('province_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province_id', 'name', name='uq_region_per_province')
    )
    op.create_table('municipalities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('regional_district_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('municipality_type', sa.Enum('CITY', 'DISTRICT_MUNICIPALITY', 'TOWN', 'VILLAGE', 'ISLAND_MUNICIPALITY', 'MOUNTAIN_RESORT_MUNICIPALITY', 'RESORT_MUNICIPALITY', 'INDIAN_GOVERNMENT_DISTRICT', 'OTHER', name='municipality_type'), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regional_district_id'], ['regional_districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regional_district_id', 'name', 'municipality_type', name='uq_municipality_per_region')
    )
    op.create_table('licenses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope', sa.Enum('MUNICIPAL', 'INTERMUNICIPAL', name='license_scope'), nullable=False),
    sa.Column('municipality_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('regional_district_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_authority', sa.String(length=150), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status_override', sa.Enum('ACTIVE', 'EXPIRING_SOON', 'EXPIRED', 'INACTIVE', 'PENDING', name='license_status'), nullable=True),
    sa.Column('warning_threshold_days', sa.Integer(), nullable=True),
    sa.Column('document_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['regional_district_id'], ['regional_districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licenses')
    op.drop_table('municipalities')
    op.drop_table('regional_districts')
    op.drop_table('provinces')
    # ### end Alembic commands ###
