"""add version_number to document_versions

Revision ID: bb7e6a2c6d6e
Revises: 20260331_0007
Create Date: 2026-04-16 17:52:54.762019
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "bb7e6a2c6d6e"
down_revision = "20260331_0007"
branch_labels = None
depends_on = None


def upgrade():
    # autogenerated by alembic - please adjust!
    # 1. Add column as NULLABLE first
    op.execute(
        "ALTER TABLE document_versions ADD COLUMN IF NOT EXISTS version_number INTEGER"
    )

    # 2. Backfill existing rows
    op.execute("""
    WITH ranked AS (
        SELECT id,
               ROW_NUMBER() OVER (
                   PARTITION BY document_id
                   ORDER BY created_at ASC
               ) AS rn
        FROM document_versions
    )
    UPDATE document_versions dv
    SET version_number = ranked.rn
    FROM ranked
    WHERE dv.id = ranked.id;
    """)

    # 3. Make column NOT NULL
    op.alter_column(
        "document_versions",
        "version_number",
        nullable=False,
    )

    # 4. Add unique constraint
    op.execute("""
    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_doc_version') THEN
            ALTER TABLE document_versions ADD CONSTRAINT uq_doc_version UNIQUE (document_id, version_number);
        END IF;
    END $$;
        """)


def downgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    table_names = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        nullable=True,
    )
    op.create_unique_constraint(
        op.f("user_roles_user_id_role_id_key"),
        "user_roles",
        ["user_id", "role_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_uploaded_by_user_id"), table_name="documents")
    op.drop_constraint("uq_doc_version", "document_versions", type_="unique")
    op.alter_column(
        "document_versions",
        "tags",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=sa.text("'[]'::json"),
        existing_nullable=False,
    )
    op.alter_column(
        "document_versions",
        "classification",
        existing_type=sa.Enum(
            "INCOMING_INVOICE",
            "OUTGOING_INVOICE",
            "INVOICE",
            "CONTRACT",
            "RECEIPT",
            "UNKNOWN",
            name="document_class_enum",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "document_versions",
        "content",
        existing_type=postgresql.BYTEA(),
        server_default=sa.text("'\\x'::bytea"),
        existing_nullable=True,
    )
    op.drop_column("document_versions", "version_number")
    if "ml_classifications" not in table_names:
        op.create_table(
            "ml_classifications",
            sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
            sa.Column(
                "document_version_id", sa.UUID(), autoincrement=False, nullable=False
            ),
            sa.Column("model_name", sa.VARCHAR(), autoincrement=False, nullable=False),
            sa.Column("label", sa.VARCHAR(), autoincrement=False, nullable=False),
            sa.Column(
                "confidence",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("ml_classifications_pkey")),
        )
        op.create_index(
            op.f("ix_ml_classifications_document_version_id"),
            "ml_classifications",
            ["document_version_id"],
            unique=False,
        )

    if "processing_jobs" not in table_names:
        op.create_table(
            "processing_jobs",
            sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
            sa.Column(
                "document_version_id", sa.UUID(), autoincrement=False, nullable=False
            ),
            sa.Column(
                "stage",
                postgresql.ENUM(
                    "CLASSIFICATION", "OCR", "POST_PROCESS", name="processing_stage"
                ),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "status",
                postgresql.ENUM(
                    "pending", "processing", "uploaded", "failed", name="processing_status"
                ),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "created_at",
                postgresql.TIMESTAMP(),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                postgresql.TIMESTAMP(),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "result",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["document_version_id"],
                ["document_versions.id"],
                name=op.f("fk_document_version"),
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("processing_jobs_pkey")),
        )
    # ### end Alembic commands ###
